// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMh_yQnXqqthh7DBzhBfHA7WaaURSpby4',
    appId: '1:393968842491:web:ef6b558905ffcb3c86a25e',
    messagingSenderId: '393968842491',
    projectId: 'flutter-chat-app-3b741',
    authDomain: 'flutter-chat-app-3b741.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3b741.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDColwDHvUVZMQEVTcEmimjDIcFLF_u02o',
    appId: '1:393968842491:android:82e257f067a1597586a25e',
    messagingSenderId: '393968842491',
    projectId: 'flutter-chat-app-3b741',
    storageBucket: 'flutter-chat-app-3b741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIpdjGnmCwjgO20T5MikU7HEj56K7HfcQ',
    appId: '1:393968842491:ios:228a3255a73a22f386a25e',
    messagingSenderId: '393968842491',
    projectId: 'flutter-chat-app-3b741',
    storageBucket: 'flutter-chat-app-3b741.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIpdjGnmCwjgO20T5MikU7HEj56K7HfcQ',
    appId: '1:393968842491:ios:228a3255a73a22f386a25e',
    messagingSenderId: '393968842491',
    projectId: 'flutter-chat-app-3b741',
    storageBucket: 'flutter-chat-app-3b741.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMh_yQnXqqthh7DBzhBfHA7WaaURSpby4',
    appId: '1:393968842491:web:81cc31e58555cf1686a25e',
    messagingSenderId: '393968842491',
    projectId: 'flutter-chat-app-3b741',
    authDomain: 'flutter-chat-app-3b741.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3b741.appspot.com',
  );
}
