name: dday
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  sqflite_common_ffi_web: ^0.4.2+4
  path: ^1.9.0
  intl: ^0.19.0
  uuid: ^4.3.3
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: true # 안드로이드 플랫폼에 런처 아이콘 적용 여부
  ios: true # iOS 플랫폼에 런처 아이콘 적용 여부
  image_path: "assets/icons/app_icon.png" # 런처 아이콘으로 사용할 이미지 경로
  adaptive_icon_background: "#000000" # 안드로이드 적응형 아이콘의 배경색 (검정색)
  adaptive_icon_foreground: "assets/icons/app_icon.png" # 안드로이드 적응형 아이콘의 전경 이미지 경로
  min_sdk_android: 21 # 안드로이드 최소 SDK 버전 (API 21(Android 5.0) 이상)

flutter_native_splash:
  color: "#FFFFFF" # 스플래시 화면의 배경색 설정 (흰색)
  image: "assets/icons/app_icon.png" # 스플래시 화면에 표시될 이미지 설정 (앱 로고)
  android: true # 안드로이드 플랫폼에 스플래시 화면 적용
  ios: true # iOS 플랫폼에 스플래시 화면 적용
  android_12: # Android 12 이상을 위한 추가 설정
    color: "#FFFFFF" # Android 12 이상 스플래시 화면의 배경색 (흰색)
    image: "assets/icons/app_icon.png" # Android 12 이상 스플래시 화면에 표시될 이미지

flutter:

  uses-material-design: true

  assets:
    - assets/icons/app_icon.png
  #   - images/a_dot_ham.jpeg
